### PR TITLE
Fix double request on rental

### LINKED ISSUE #188: Fix double request on new rental
When starting a rental (typing a tag on the Scan screen and pressing Rent), during the transition from the Scan screen to the Rental Details screen, two identical `GET` requests are made for the added item.

Based on my simple debugging, one of them seems to come from `Rental.onAdd()` and the other from `Home.onNext()`.

### PR DESCRIPTION
**Pull request by emmanuelroussel**
Closes #188

### CODE REVIEW

File: src/pages/home/home.ts [hunk 1]
```diff
@@ -64,7 +64,7 @@ export class HomePage {
       alert.present();
     } else {
       this.navCtrl.push(RentalPage, {
-        tag: this.tag,
+        item: item,
```
Comment (AdamVig) [inline src/pages/home/home.ts]: Just `item` here!
