### PR TITLE
134/Change API URL constant to a service

### LINKED ISSUE #134: Fix wrong API URL on devices/emulators
See #114 for in-depth discussion of this issue.

The important points of the discussion:

@adamvig:
> It seems that the URLs are not being constructed properly, so the HTTP provider is defaulting to using the file:// protocol.
> 
> After further testing, I have identified that the problem is the ApiUrl constant being set to a relative URL (/api). This works fine for development in-browser, where we use the Ionic proxy to avoid CORS issues, but the proxy does not work on the device (source).
> 
> We may be able to use Ionic's platform detection to dynamically change the API URL based on the current platform. This would require changing the structure of the constants file to be more like a component. Another option is to make Webpack change the URL based on the build target. @emmanuelroussel any feedback on these options?

@emmanuelroussel:
> Webpack would make more sense, but we currently can't change the config (related issue on ionic-app-scripts repo). The other temporary solutions require rollup which is overkill for what we need and requires lots of setup or copy and pasting Ionic's webpack config and changing it manually which is also .
> 
> Not sure what the best solution is. Maybe we can change the url from a constant to a function that returns the appropriate url depending on the platform as you mentioned.

### PR DESCRIPTION
**Pull request by AdamVig**
This enables the returned API URL to change depending on the platform it
is running on.

Closes #134.

### CODE REVIEW

File: src/mocks.ts [hunk 1]
```diff
@@ -85,6 +91,18 @@ export class PlatformMock {
   }
 }
 
+export class PlatformMockIsCore {
+  public is(platform: string): Boolean {
+    return platform === 'core'
+  }
+}
+
+export class PlatformMockIsAndroid {
```
Comment (emmanuelroussel) [inline src/mocks.ts]: Instead of creating both of these mocks, you could modify `PlatformMock` to have an attribute `platform`, add the method `is(platform: string)` and compare the class variable of the class with the parameter.

That way, you don't have to create a new instance of apiUrl with the appropriate mock for every test. You can instead assign the platform you want like this: `apiUrl.platform.platform = 'android'` and initialize `apiUrl` in `beforeEach()`.

You can look at other mocks that have a `resolve` variable if this explanation is not clear.

Comment (AdamVig) [inline src/mocks.ts]: This is great feedback, thanks! I made the change.
